### PR TITLE
README.md update

### PR DESCRIPTION
**Pull request by okkidwi**
Are you planning to make the premium version? 🤔

### CODE REVIEW

**Comment by wong2** [comment]
Thanks, please move `chrome_button_icon.png` outside of `src`, it doesn't belong there.

**Comment by okkidwi** [comment]
> Thanks, please move `chrome_button_icon.png` outside of `src`, it doesn't belong there.

Ok, sorry. I'll fix it

**Comment by okkidwi** [comment]
> > Thanks, please move `chrome_button_icon.png` outside of `src`, it doesn't belong there.
> 
> Ok, sorry. I'll fix it

I'm done @wong2

**Comment by wong2** [comment]
Thanks

**Pull request merged**
