### PR TITLE
Add Claude 2 (Fixes #654, Fixes #646)

### LINKED ISSUE #646: 手机kiwi浏览器用Claude闪退
**Describe the bug**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Browser [e.g. chrome, brave]

### LINKED ISSUE #654: Claude2.0 官方界面已支持多文件上传，目前HUB界面没跟进
image

这个功能非常好用！建议更新

### PR DESCRIPTION
**Pull request by Explosion-Scratch**

### CODE REVIEW

**Comment by wong2** [comment]
Sorry, this is already implemented in my branch

**Comment by Explosion-Scratch** [comment]
@wong2 Your version requires an API key which many people don't have as Claude's official API is in beta. This PR adds support for the unofficial API via their web interface. Seeing as you already support ChatGPT's unofficial API as well I think that including the unofficial API of Claude would at least be good as an option (toggle on/off)

**Comment by wong2** [comment]
https://github.com/chathub-dev/chathub/tree/token/src/app/bots/claude-web

I've also implemented the unofficial API version.

**Comment by Explosion-Scratch** [comment]
Awesome thanks

**Pull request closed without merging**
