### PR TITLE
Adjust copy button to sticky

### PR DESCRIPTION
**Pull request by C-Dao**

### CODE REVIEW

**Comment by wong2** [comment]
Thanks, but I want the button to be centered instead at the top

**Comment by C-Dao** [comment]
> Thanks, but I want the button to be centered instead at the top

If putting the button on the center, when the message box is too long, user can not find the button fine and the experience is not good. Putting the button on top and making it sticky and be followed the message box moving, these can allow user quickly click button😊

**Comment by wong2** [comment]
Thanks, I'll consider that.

**Comment by wong2** [comment]
Oh, I've just implemented it.

**Pull request closed without merging**
