### PR TITLE
3 pane to show ChatGPT / Bing / Bard all together

### PR DESCRIPTION
**Pull request by iamzhout**
by this way we can compare ChatGPT / Bing / Badr more conveniently.

image

### CODE REVIEW

**Comment by wong2** [comment]
Most users don't have such a large screen..

**Comment by iamzhout** [comment]
> Most users don't have such a large screen..

Yep, so it may be best to have an option for users to choose whether to display two screens or three screens.

**Comment by ntz857** [comment]
> > Most users don't have such a large screen..
> 
> Yep, so it will be better to have an option for users to choose whether to display two screens or three.

agree~

**Comment by iamzhout** [comment]
@wong2 I have updated the PR for both '2-in-1' and '3-in-1' display as shown below:
image


Since I have no prior experience on frontend development, there still exist two problems, please help to take a review and maybe fix them?

problem 1:  switch between '2-in-1' & '3-in-1' will cause error everytime, and take a refresh will fix 
image

problem 2: '3-in-1' display panels vertically but not horizontally, I don't know why variable `${cols}` in MultiBotChatPanel.tsx doesn't work ..
```<div className={`grid grid-cols-${cols} gap-5 overflow-hidden grow`}>```
image

**Comment by grandmavaddi** [comment]
> by this way we can compare ChatGPT / Bing / Badr more conveniently.
> 
> image

This looks great please implement this that would be great !

**Comment by wong2** [comment]
Thanks, I've implemented this in the latest version

**Pull request closed without merging**
