### PR TITLE
Add Dark Mode Feature

### PR DESCRIPTION
**Pull request by C-Dao**
Hello, I add dark mode feature for chathub, and the color of the dark theme maybe not fine, if you have the best color of dark theme, you can change my code. I am glad to you reply.

### CODE REVIEW

**Comment by C-Dao** [comment]
Hello, can you notice my pull request? If you need my help, you can tell me, and I will change these codes and polish them. I am very happy to deal with it. thank you for your so awesome product. @wong2

**Comment by Geczy** [comment]
@C-Dao can you fix the conflicts

**Comment by C-Dao** [comment]
Yes, I do it

**Comment by C-Dao** [comment]
Hello, I resolved these conflicts. Please take a look

**Comment by wong2** [comment]
Hey sorry for not responding to this, dark mode is a burden to maintain, so I'm very cautious to add it.

**Comment by C-Dao** [comment]
> Hey sorry for not responding to this, dark mode is a burden to maintain, so I'm very cautious to add it.

Thanks for your late reply

**Comment by Geczy** [comment]
?? why is it a burden, the pr was already finished and added some amazing css improvements like var from css

**Pull request closed without merging**
